UPDATE public.disease_docs SET content = 'Caused by the soil-borne bacterium Ralstonia solanacearum. Plants wilt suddenly while leaves stay green; cut stems ooze milky bacterial strands in water and show brown vascular staining. Spread by infested soil, water runoff, tools and seedlings. Management: uproot and destroy affected plants with surrounding soil, avoid replanting solanaceous crops for 3 seasons, improve drainage and raised beds, use grafted or tolerant varieties, disinfect tools with bleach. No effective chemical cure.' WHERE title = 'Bacterial Wilt' AND crop = 'Pepper';

UPDATE public.disease_docs SET content = 'Caused by Mycosphaerella fijiensis (Pseudocercospora fijiensis). Begins as tiny reddish-brown specks that lengthen into dark streaks, then grey lesions with yellow halos; heavy infection kills the leaf canopy and forces premature fruit ripening. Favoured by high humidity, dense mats and poor air flow. Management: deleaf and destroy infected leaves weekly, wider spacing, good drainage, balanced potassium, resistant hybrids, and rotate systemic fungicides (propiconazole, azoxystrobin) with protectant mancozeb to avoid resistance.' WHERE title = 'Black Sigatoka';

UPDATE public.disease_docs SET content = 'Caused by cassava mosaic begomoviruses (ACMV, EACMV-UG) spread by the whitefly Bemisia tabaci and by planting infected cuttings. Symptoms: yellow-green mosaic mottling, twisted and misshapen leaflets, reduced leaf area and stunted plants; root yield can fall by 20-90%. No chemical cure. Management: plant certified CMD-resistant varieties (NASE 14, NAROCASS 1), take cuttings only from healthy plants, rogue and burn symptomatic plants early, control whitefly, and avoid planting next to old infected fields.' WHERE title = 'Cassava Mosaic Disease';

UPDATE public.disease_docs SET content = 'Caused by Alternaria solani. Dark brown spots with concentric target-like rings and yellow margins, starting on older lower leaves and moving upward; stems show dark collar rot and fruit develops sunken leathery lesions at the stem end. Favoured by warm days, dew and alternating wet-dry spells. Management: rotate away from tomato/potato for 2-3 years, mulch, stake and prune for airflow, water at the base in the morning, remove lower infected leaves, and spray chlorothalonil, mancozeb or difenoconazole preventively at first fruit set.' WHERE title = 'Early Blight' AND crop = 'Tomato';

UPDATE public.disease_docs SET content = 'Caused by the oomycete Phytophthora infestans. Water-soaked grey-green blotches on leaf tips and margins turn brown-black with a pale halo and white downy growth on the underside in humid weather; stems blacken and tubers develop reddish-brown granular rot beneath the skin. Spreads explosively in cool wet conditions (12-20C, long leaf wetness). Management: use certified clean seed tubers and resistant varieties, hill soil over tubers, destroy volunteer plants and cull piles, and apply mancozeb protectively then metalaxyl or cymoxanil-based sprays when blight risk is high. Harvest only after haulms are fully dead.' WHERE title = 'Late Blight' AND crop = 'Potato';

UPDATE public.disease_docs SET content = 'Caused by Maize streak virus, transmitted persistently by Cicadulina leafhoppers from grasses. Symptoms: fine pale-yellow broken streaks running parallel to the veins, merging into continuous chlorotic stripes; early infection causes severe stunting and barren or poorly filled cobs. No chemical cure for the virus. Management: plant streak-tolerant varieties (Longe 5, Longe 10H), sow early and uniformly in the season, remove grass weeds and volunteer maize around fields, avoid staggered late planting near infected crops, and use seed treated with a systemic insecticide to slow leafhopper feeding.' WHERE title = 'Maize Streak Virus';

UPDATE public.disease_docs SET content = 'Caused by Exserohilum turcicum. Long cigar-shaped grey-green to tan lesions 3-15 cm on the leaves, starting low and moving up; heavy infection before silking greys the whole canopy and cuts grain fill sharply. Favoured by moderate temperatures, heavy dew and maize residue left on the surface. Management: plant resistant hybrids, rotate with legumes, bury or remove residue, avoid dense planting, and spray azoxystrobin or propiconazole from tasseling when lesions reach the ear leaf on susceptible varieties.' WHERE title = 'Northern Leaf Blight';

UPDATE public.disease_docs SET content = 'Caused by Tomato yellow leaf curl virus group begomoviruses, transmitted by the whitefly Bemisia tabaci. Symptoms: upward curling and cupping of small leaves, yellow leaf margins, shortened internodes and bushy stunted plants, flower drop and very poor fruit set. No chemical cure. Management: raise seedlings under insect-proof netting, plant tolerant varieties, use silver reflective mulch and yellow sticky traps, rogue infected plants immediately, keep a crop-free break between cycles, and control whitefly with rotated insecticides plus insecticidal soap.' WHERE title = 'Tomato Leaf Curl Virus';